// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 astarat-code
/**
 * AvatarIcon.jsx — Avatars of the epic, indexed on TOTAL CAPITAL.
 *
 * Usage: <AvatarIcon capital={42000} size={48} />          (automatic resolution)
 *        <AvatarIcon tier="dragon" isPrestige size={32} />  (explicit override)
 *
 * Tiers and chapters: avatarService. Paths and licenses: avatarIcons.js
 * (generated by scripts/generate-avatar-icons.js).
 *
 * Color: the one of the tier's chapter — it climbs from green to magenta along the epic.
 * Gold is reserved for the Legend (beyond €1M), which adds a ring.
 */

import { getAvatarForCapital, AVATAR_STEPS } from '../../services/avatarService';
import { AVATAR_ICONS } from './avatarIcons';

const GOLD  = '#F59E0B';
const GOLD2 = '#D97706';

/**
 * Couleur par chapitre. Contraste vérifié ≥ 4:1 sur le fond clair comme sur le
 * fond sombre de l'application (l'icône n'a pas de fond propre).
 */
const COULEUR_CHAPITRE = {
  1: '#059669', // L'Éveil — émeraude
  2: '#0284C7', // Le Voyage — bleu ciel
  3: '#6366F1', // La Chevalerie — indigo
  4: '#8B5CF6', // La Conquête — violet
  5: '#C026D3', // Les Étoiles — magenta
};

const CHAPITRE_DU_PALIER = Object.fromEntries(AVATAR_STEPS.map(s => [s.tier, s.chapitre]));
const PALIER_PAR_DEFAUT = AVATAR_STEPS[0].tier;

/**
 * @param {object} props
 * @param {number} [props.capital]    — capital total (résout palier + Légende)
 * @param {string} [props.tier]       — override : clé de palier ('dragon', 'sommet'…)
 * @param {boolean}[props.isGolden]   — override or (réservé à la Légende en usage normal)
 * @param {boolean}[props.isPrestige] — override liseré d'or (> 1 M€)
 * @param {number} [props.size]       — taille px (32 | 48 | 64 | 96), défaut 40
 * @param {string} [props.className]  — classes Tailwind supplémentaires
 * @param {boolean}[props.withFlame]  — affiche flamme animée si vrai
 * @param {string} [props.title]      — infobulle (défaut : libellé du palier)
 */
export default function AvatarIcon({
  capital, tier, isGolden, isPrestige,
  size = 40, className = '', withFlame = false, title,
}) {
  let resolvedTier = tier;
  let prestige     = isPrestige ?? false;
  let golden       = isGolden ?? prestige;
  let label        = tier;

  if (capital !== undefined && !tier) {
    const info = getAvatarForCapital(capital);
    resolvedTier = info.tier;
    prestige     = isPrestige !== undefined ? isPrestige : info.isPrestige;
    golden       = isGolden   !== undefined ? isGolden   : info.isGolden;
    label        = info.labelFr;
  }

  const cle     = AVATAR_ICONS[resolvedTier] ? resolvedTier : PALIER_PAR_DEFAUT;
  const icone   = AVATAR_ICONS[cle];
  const couleur = golden ? GOLD : COULEUR_CHAPITRE[CHAPITRE_DU_PALIER[cle]];

  // Liseré d'or plein de la Légende : anneau, halo léger, et une marge intérieure
  // pour que l'icône ne touche pas le cercle.
  const epaisseur = prestige ? Math.max(2, Math.round(size * 0.055)) : 0;
  const marge     = prestige ? Math.round(size * 0.12) : 0;

  return (
    <span
      className={`relative inline-flex items-center justify-center ${className}`}
      style={{
        width: size,
        height: size,
        flexShrink: 0,
        boxSizing: 'border-box',
        color: couleur,
        ...(prestige ? {
          borderRadius: '9999px',
          border: `${epaisseur}px solid ${GOLD}`,
          boxShadow: `0 0 0 1px ${GOLD2}, 0 0 ${Math.round(size * 0.18)}px rgba(245,158,11,0.45)`,
          padding: marge,
        } : {}),
      }}
      title={title || label || resolvedTier}
    >
      <svg
        viewBox={icone.viewBox}
        width="100%"
        height="100%"
        fill="currentColor"
        aria-hidden="true"
        focusable="false"
      >
        {icone.traces.map((d, i) => <path key={i} d={d} />)}
      </svg>
      {withFlame && (
        <span
          className="absolute -top-1 -right-1 text-sm leading-none select-none"
          style={{ animation: 'flamePulse 1.5s ease-in-out infinite' }}
        >
          🔥
        </span>
      )}
    </span>
  );
}
