// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 astarat-code
/**
 * displayNote.js — Display label of a movement note.
 *
 * Occurrences generated by a recurring series are stored with the "[Mouvement récurrent]"
 * prefix. That prefix also acts as a marker in the data: it is not rewritten, only
 * translated at display time.
 */
const RECURRING_PREFIX = '[Mouvement récurrent]';

export function displayNote(note, lang) {
  if (!note || lang !== 'en' || !note.startsWith(RECURRING_PREFIX)) return note;
  return `[Recurring movement]${note.slice(RECURRING_PREFIX.length)}`;
}

export default displayNote;
